// <auto-generated />
using GPScript.NET.src.infraestructura.datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GPScript.NET.src.infraestructura.datos.migraciones
{
    [DbContext(typeof(ContextoDatos))]
    [Migration("20250712125350_AppDbMigrations")]
    partial class AppDbMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GPScript.NET.src.dominio.modelos.DatosDePredicciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaRiesgo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("DiasDemoraPredicho")
                        .HasColumnType("real");

                    b.Property<float>("DiasDemoraRealPromedio")
                        .HasColumnType("real");

                    b.Property<float>("DiferenciaDias")
                        .HasColumnType("real");

                    b.Property<string>("NombreEnte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromedioFinComInicioFactura")
                        .HasColumnType("integer");

                    b.Property<int>("PromedioInicioComFinCom")
                        .HasColumnType("integer");

                    b.Property<int>("PromedioInicioComFinPagado")
                        .HasColumnType("integer");

                    b.Property<int>("PromedioInicioFacturaFinPagado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DatosDePredicciones");
                });
#pragma warning restore 612, 618
        }
    }
}
